networks:
   web:
      external: true
   internal:
      external: false

services:
   tracker:
      build:
         context: .
         dockerfile: Dockerfile
      container_name: tracker
      restart: unless-stopped
      env_file: .env
      labels:
         - "traefik.enable=true"
         - "traefik.http.routers.tracker.rule=Host(`${DOMAIN}`)"
         - "traefik.http.routers.tracker.entrypoints=websecure"
         - "traefik.http.routers.tracker.tls=true"
      networks:
         - internal
         - web
      depends_on:
         - mysql-db
      volumes:
         - '/etc/localtime:/etc/localtime:ro'
         - '/etc/timezone:/etc/timezone:ro'

   mysql-db-tracker:
      image: mysql:8.0
      container_name: mysql-db-tracker
      restart: unless-stopped
      env_file: .env
      environment:
         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
         MYSQL_DATABASE: ${DB_DATABASE}
         MYSQL_ROOT_HOST: '%'
         TZ: Europe/Berlin
      networks:
         - internal
      labels:
         - traefik.enable=false
      volumes:
         - mysql-data:/var/lib/mysql

   mysql-backup-tracker:
      image: fradelg/mysql-cron-backup
      container_name: mysql-backup-tracker
      restart: unless-stopped
      env_file: .env
      environment:
         MYSQL_HOST: mysql-db
         MYSQL_PORT: 3306
         MYSQL_USER: ${DB_USERNAME}
         MYSQL_PASS: ${DB_PASSWORD}
         MYSQL_DB: ${DB_DATABASE}
         CRON_TIME: '0 3 * * *'
         MAX_BACKUPS: 3
         GZIP_BACKUP: true
         TZ: Europe/Berlin
      volumes:
         - ./db-backups:/backup
      depends_on:
         - mysql-db
      networks:
         - internal

volumes:
   mysql-data:
